export const LIBRARY_TEMPLATE = `\
// Auto-generated by solgate from <%- gateName %>.gate
// DO NOT EDIT — re-run \`solgate codegen\` to regenerate
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Vm} from "forge-std/Vm.sol";
import {Solgate} from "solgate/Solgate.sol";

library <%- libName %> {
    using Solgate for Solgate.Gate;

    Vm constant VM = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

<% if (params.length > 0) { -%>
    // ─── Params ───

<% for (const param of params) { -%>
    function <%- param.fnName %>(Solgate.Gate memory gate, <%- param.solType %> value) internal {
        gate.setParam("<%- param.name %>", value);
    }

<% } -%>
<% } -%>
<% if (eventSources.length > 0) { -%>
    // ─── Event Sources ───

<%- eventSources.join('') -%>
<% } -%>
<% if (callSources.length > 0) { -%>
    // ─── Call Sources ───

<%- callSources.join('') -%>
<% } -%>
}
`;

export const LIST_PREAMBLE_TEMPLATE = `\
            string memory <%- listVar %> = "[";
            for (uint256 <%- loopVar %> = 0; <%- loopVar %> < <%- accessor %>.length; <%- loopVar %>++) {
                if (<%- loopVar %> > 0) <%- listVar %> = string.concat(<%- listVar %>, ",");
                <%- listVar %> = string.concat(<%- listVar %>, <%- elemContent %>);
            }
            <%- listVar %> = string.concat(<%- listVar %>, "]");
`;

export const LIST_SCALAR_FN_TEMPLATE = `\
    function <%- fnName %>(Solgate.Gate memory gate, <%- solType %>[] memory values) internal {
        string memory json = "[";
        for (uint256 i = 0; i < values.length; i++) {
            if (i > 0) json = string.concat(json, ",");
            json = string.concat(json, <%- elemExpr %>);
        }
        json = string.concat(json, "]");
        gate.mockRaw("<%- sourceName %>", json);
    }

`;

export const SERIALIZE_BODY_TEMPLATE = `\
        string memory json = "[";
        for (uint256 i = 0; i < <%- varName %>.length; i++) {
            if (i > 0) json = string.concat(json, ",");
<%- preambles -%>
<%- concatCall -%>
        }
        json = string.concat(json, "]");
        gate.mockRaw("<%- sourceName %>", json);
`;
